export class Config {
  static baseurl = "http://52.193.1.160";
  static version = '9.9.12';
  static isdebug = true;
  static inviteCode = 'app_liudehua'; // 208793, disable update check
  static openRegist = true;
  static needLoginToView = false;
  static bankcardIconMap = {
    "工商银行": "assets/img/bank/gongshang.svg",
    "建设银行": "assets/img/bank/jianshe.svg",
    "农业银行": "assets/img/bank/nongye.svg",
    "银行": "assets/img/bank/zhongguo.svg",
    "光大银行": "assets/img/bank/guangda.svg",
    "邮政储蓄银行": "assets/img/bank/youzheng.svg",
    "中国邮政储蓄": "assets/img/bank/youzheng.svg",
    "交通银行": "assets/img/bank/jiaotong.svg",
    "民生银行": "assets/img/bank/mingsheng.svg",

    "中国工商银行": "assets/img/bank/gongshang.svg",
    "中国建设银行": "assets/img/bank/jianshe.svg",
    "中国农业银行": "assets/img/bank/nongye.svg",
    "中国银行": "assets/img/bank/zhongguo.svg",
    "招商银行": "assets/img/bank/zhaoshang.svg",
    "中国交通银行": "assets/img/bank/jiaotong.svg",
    "中国民生银行": "assets/img/bank/mingsheng.svg",
    "中信银行": "assets/img/bank/zhongxin.svg",
    "上海浦东发展银行": "assets/img/bank/pufa.svg",
    "广东发展银行": "assets/img/bank/guangfa.svg",
    "平安银行": "assets/img/bank/pingan.svg",
    "兴业银行": "assets/img/bank/xingye.svg",
    "华夏银行": "assets/img/bank/huaxia.svg",
    "中国光大银行": "assets/img/bank/guangda.svg",
    "中国邮政储蓄银行": "assets/img/bank/youzheng.svg",
    "财付通": "assets/img/bank/caifutong.svg",

    "上海银行": "assets/img/bank/shanghai.svg",
    "北京银行": "assets/img/bank/beijing.svg",
    "江苏银行": "assets/img/bank/jiangsu.svg",
    "宁波银行": "assets/img/bank/ningbo.svg",
    "深圳发展银行": "assets/img/bank/shenfa.svg",
    "温州银行": "assets/img/bank/wenzhou.svg",
    "杭州银行": "assets/img/bank/hangzhou.svg",
    "金华银行": "assets/img/bank/jinhua.svg",

    "恒丰银行": "assets/img/bank/hengfeng.svg",
    "郑州银行": "assets/img/bank/zhengzhou.svg",
    "包商银行": "assets/img/bank/baoshang.svg",
    "福建海峡银行": "assets/img/bank/fujianhaixia.svg",
    "嘉兴银行": "assets/img/bank/jiaxing.svg",
    "绍兴银行": "assets/img/bank/shaoxing.svg",
  };
  static bankcardIconMapPNG = {
    "工商银行": "assets/img/bank/gongshang.png",
    "建设银行": "assets/img/bank/jianshe.png",
    "农业银行": "assets/img/bank/nongye.png",
    "银行": "assets/img/bank/zhongguo.png",
    "光大银行": "assets/img/bank/guangda.svg",
    "邮政储蓄银行": "assets/img/bank/youzheng.png",
    "中国邮政储蓄": "assets/img/bank/youzheng.png",
    "交通银行": "assets/img/bank/jiaotong.png",
    "民生银行": "assets/img/bank/mingsheng.png",

    "中国工商银行": "assets/img/bank/gongshang.png",
    "中国建设银行": "assets/img/bank/jianshe.png",
    "中国农业银行": "assets/img/bank/nongye.png",
    "中国银行": "assets/img/bank/zhongguo.png",
    "招商银行": "assets/img/bank/zhaoshang.png",
    "中国交通银行": "assets/img/bank/jiaotong.png",
    "中国民生银行": "assets/img/bank/mingsheng.png",
    "中信银行": "assets/img/bank/zhongxin.svg",
    "上海浦东发展银行": "assets/img/bank/pufa.svg",
    "广东发展银行": "assets/img/bank/guangfa.svg",
    "平安银行": "assets/img/bank/pingan.svg",
    "兴业银行": "assets/img/bank/xingye.svg",
    "华夏银行": "assets/img/bank/huaxia.svg",
    "中国光大银行": "assets/img/bank/guangda.svg",
    "中国邮政储蓄银行": "assets/img/bank/youzheng.png",
    "财付通": "assets/img/bank/caifutong.svg",

    "上海银行": "assets/img/bank/shanghai.svg",
    "北京银行": "assets/img/bank/beijing.svg",
    "江苏银行": "assets/img/bank/jiangsu.svg",
    "宁波银行": "assets/img/bank/ningbo.svg",
    "深圳发展银行": "assets/img/bank/shenfa.svg",
    "温州银行": "assets/img/bank/wenzhou.svg",
    "杭州银行": "assets/img/bank/hangzhou.svg",
    "金华银行": "assets/img/bank/jinhua.svg",

    "恒丰银行": "assets/img/bank/hengfeng.svg",
    "郑州银行": "assets/img/bank/zhengzhou.svg",
    "包商银行": "assets/img/bank/baoshang.svg",
    "福建海峡银行": "assets/img/bank/fujianhaixia.svg",
    "嘉兴银行": "assets/img/bank/jiaxing.svg",
    "绍兴银行": "assets/img/bank/shaoxing.svg",
  };
}
