// 圆角分
// const modes = {1: '元', 2: '角', 3: '分', 4: '厘'};
const modes = {1: '元', 2: '角'};
// const modes2 = {1: '元', 2: '角', 3: '分'};
const modes2 = {1: '元', 2: '角'};
const digitalPos = {'w': '万位', 'q': '千位', 'b': '百位', 's': '十位', 'g': '个位'};
export var lotteries = {
  dfmmc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '大丰秒秒彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=dfmmc&count=30',
    // 'desc': '随时投随时开',
    'desc': '1秒钟一次',
    'fastopen': true,
    'selfopen': true,
    'modes': modes2,
    'tag': 'N'
  },
  dfffc: {
    'icon': '../assets/imgs/home/game-logo/logo-ffc.png',
    'dyprize': true,
    'name': '大丰分分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'QDXDS',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=dfffc&count=30',
    // 'desc': '04:00-02:00每分钟一期，全天1320期',
    'desc': '5分钟一期',
    'selfopen': true,
    'modes': modes,
    'tag': 'N'
  },
  txffc: {
    'icon': '../assets/imgs/home/game-logo/logo-ffc.png',
    'dyprize': true,
    'name': '腾讯分分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=txffc&count=30',
    'desc': '1分钟一期',
    'selfopen': true,
    'modes': modes2,
    'tag': 'N'
  },
  dfssc: {
    'icon': '../assets/imgs/home/game-logo/logo-3fc.png',
    'dyprize': true,
    'name': '大丰三分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=dfssc&count=30',
    'desc': '04:00-02:00每3分钟一期，全天440期',
    'selfopen': true,
    'modes': modes,
    'tag': 'N'
  },
  hgssc: {
    'icon': '../assets/imgs/home/game-logo/logo-3fc.png',
    'dyprize': true,
    'name': '大丰三分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=hgssc&count=30',
    'desc': '04:00-02:00每3分钟一期，全天440期',
    'selfopen': true,
    'modes': modes,
    'tag': 'N'
  },

  df30: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    "dyprize": true,
    "name": "大丰30秒",
    "pattern": "digital",
    "type": 1,
    "len": 5,
    "default_methodid": "HZX3",
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=df30&count=30',
    'desc': '04:00-02:00每30秒一期，全天2640期',
    'selfopen': true,
    'modes': modes,
    'tag': 'N'
  },
  df3d: {
    'icon': '../assets/imgs/home/game-logo/logo-3fc.png',
    "dyprize": true,
    "name": "分分3D",
    "pattern": "digital3",
    "type": 3,
    "len": 3,
    "default_methodid": "ZX3",
    'trend': '/trend?lotteryid=df3d&count=30',
    // 'desc': '04:00-02:00每分钟一期，全天1320期',
    'desc': '1分钟一期',
    'selfopen': true,
    'modes': modes,
    'tag': 'N'
  },
  "df28": {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    "dyprize": true,
    "name": "丰狂28",
    "pattern": "df28",
    "type": 3,
    "len": 3,
    "default_methodid": "ZXHZ",
    'trend': '/trend?lotteryid=df28&count=30',
    'desc': '04:00-02:00每3分钟一期，全天440期',
    'selfopen': true,
    'custom': true,
    'pool': true,
    'modes': modes
  },
  cqssc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '重庆时时彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=cqssc&count=30',
    'desc': '20分钟一期',
    'tag': 'H',
    'modes': modes
  },
  xjssc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '新疆时时彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=xjssc&count=30',
    'desc': '20分钟一期',
    'tag': 'H',
    'modes': modes
  },
  hljssc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '黑龙江时时彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=hljssc&count=30',
    'desc': '05:00-22:40每10分钟一期，全天84期',
    'modes': modes
  },
  tjssc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '天津时时彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=tjssc&count=30',
    'desc': '05:00-23:00每10分钟一期，全天84期',
    'modes': modes
  },
  jxssc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '江西时时彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=jxssc&count=30',
    'desc': '05:00-23:00每10分钟一期，全天84期',
    'modes': modes
  },
  sd115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '山东11选5',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=sd115&count=30',
    // 'desc': '05:00-21:55每10分钟一期，全天78期',
    'desc': '20分钟一期',
    'modes': modes
  },
  jx115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '江西多乐彩',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=jx115&count=30',
    // 'desc': '05:00-22:00每10分钟一期，全天78期',
    'desc': '20分钟一期',
    'modes': modes
  },
  sx115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '山西多乐彩',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=sx115&count=30',
    'desc': '20分钟一期',
    'modes': modes
  },
  df115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '好运11选5',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=df115&count=30',
    'desc': '20分钟一期',
    'modes': modes
  },
  gd115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '广东11选5',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=gd115&count=30',
    'desc': '20分钟一期',
    'modes': modes

  },
  sh115: {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '上海11选5',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=gd115&count=30',
    'desc': '20分钟一期',
    'modes': modes

  },
  'cq115': {
    'icon': '../assets/imgs/home/game-logo/logo-11n5.png',
    'dyprize': true,
    'name': '重庆11选5',
    'pattern': 'lotto',
    'type': 2,
    'len': 5,
    'point': 7.0,
    'default_methodid': 'LTZX3',
    'trend': '/trend?lotteryid=cq115&count=30',
    'desc': '05:00-23:00(10钟)，全天84期',
    'modes': modes

  },
  fc3d: {
    'icon': '../assets/imgs/home/game-logo/logo-fc3d.png',
    'dyprize': true,
    'name': '福彩3D',
    'pattern': 'digital3',
    'type': 3,
    'len': 3,
    'default_methodid': 'ZX3',
    'trend': '/trend?lotteryid=fc3d&count=30',
    'desc': '1天一期',
    'modes': modes
  },
  shssl: {
    'icon': '../assets/imgs/home/game-logo/logo-ffc.png',
    'dyprize': true,
    'name': '上海时时乐',
    'pattern': 'digital3',
    'type': 3,
    'len': 3,
    'default_methodid': 'ZX3',
    'trend': '/trend?lotteryid=shssl&count=30',
    'desc': '05:00-21:30 每30分钟一期，全天23期',
    'modes': modes
  },
  jskl3: {
    'icon': '../assets/imgs/home/game-logo/logo-k3.png',
    'dyprize': true,
    'name': '江苏快三',
    'pattern': 'ks',
    'type': 4,
    'len': 3,
    'default_methodid': 'KSHZ',
    'trend': '/trend?lotteryid=jskl3&count=30',
    'desc': '20分钟一期',
    'modes': modes

  },
  ahkl3: {
    'icon': '../assets/imgs/home/game-logo/logo-k3.png',
    'dyprize': true,
    'name': '安徽快三',
    'pattern': 'ks',
    'type': 4,
    'len': 3,
    'default_methodid': 'KSHZ',
    'trend': '/trend?lotteryid=ahkl3&count=30',
    'desc': '08:37-22:07每10分钟一期，全天82期',
    'modes': modes

  },
  p3p5: {
    'icon': '../assets/icon/pl355.png',
    'dyprize': true,
    'name': '排列三、五',
    'pattern': 'p3p5',
    'type': 5,
    'len': 5,
    'default_methodid': 'QZX3',
    'trend': '/trend?lotteryid=p3p5&count=30',
    'desc': '1天一期',
    'modes': modes
  },
  pk10: {
    'icon': '../assets/icon/bj10.png',
    'dyprize': true,
    'name': '北京PK拾',
    'pattern': 'pk10',
    'type': 3,
    'len': 10,
    'default_methodid': 'QZX1',
    'trend': '/trend?lotteryid=pk10&count=30',
    'desc': '20分钟一期',
    'modes': modes
  },

  dnpk10: {
    'icon': '../assets/icon/bj10.png',
    'dyprize': true,
    'name': '北京PK拾',
    'pattern': 'pk10',
    'type': 3,
    'len': 10,
    'default_methodid': 'QZX1',
    'trend': '/trend?lotteryid=dnpk10&count=30',
    'desc': '20分钟一期',
    'modes': modes
  },
  dfpk10: {
    'icon': '../assets/icon/bj10.png',
    'dyprize': true,
    'name': '北京PK拾',
    'pattern': 'pk10',
    'type': 3,
    'len': 10,
    'default_methodid': 'QZX1',
    'trend': '/trend?lotteryid=dfpk10&count=30',
    'desc': '5分钟一期',
    'modes': modes
  },
  jspk10: {
    'icon': '../assets/icon/jspk10.png',
    'dyprize': true,
    'name': '极速赛车',
    'pattern': 'pk10',
    'type': 3,
    'len': 10,
    'default_methodid': 'QZX1',
    'trend': '/trend?lotteryid=jspk10&count=30',
    'desc': '3分钟一期',
    'modes': modes
  },
  xyft: {
    'icon': '../assets/icon/jspk10.png',
    'dyprize': true,
    'name': '幸运飞艇',
    'pattern': 'pk10',
    'type': 3,
    'len': 10,
    'default_methodid': 'QZX1',
    'trend': '/trend?lotteryid=xyft&count=30',
    'desc': '5分钟一期',
    'modes': modes
  },
  hn5fc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '河内五分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=hn5fc&count=30',
    // 'desc': '随时投随时开',
    'desc': '5分钟一次',
    'fastopen': true,
    'selfopen': true,
    'modes': modes2,
    'tag': 'N'
  },
  hkffc: {
    'icon': '../assets/imgs/home/game-logo/logo-ssc.png',
    'dyprize': true,
    'name': '香港1分彩',
    'pattern': 'digital',
    'type': 1,
    'len': 5,
    'default_methodid': 'HZX3',
    'hasrx': true,
    'positions': digitalPos,
    'trend': '/trend?lotteryid=hkffc&count=30',
    // 'desc': '随时投随时开',
    'desc': '5分钟一次',
    'fastopen': true,
    'selfopen': true,
    'modes': modes2,
    'tag': 'N'
  }
};
